In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
import torch
import numpy as np

### Frobenius Norm

$ \|A\|_{F}=\left(\sum_{i, j=1}^{n}\left|a_{i j}\right|^{2}\right)^{1 / 2} $

In [4]:
# m.pow(2).sum().sqrt()
m = torch.tensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
f_norm = (m*m).sum().sqrt()
f_norm

tensor(16.8819)

### LogSumExp Trick

In [5]:
def log_softmax(x):
    return x - x.exp().sum(dim=1, keepdim=True).log()

In [6]:
x = torch.randn((5, 10))

In [7]:
log_softmax(x)

tensor([[-3.9745, -1.9283, -1.8805, -3.5326, -4.6810, -0.7468, -4.0603, -2.0907,
         -3.9964, -4.4486],
        [-1.4806, -2.7260, -3.4181, -5.7936, -2.8813, -4.7144, -0.8175, -3.8692,
         -2.3374, -3.0540],
        [-4.4816, -1.3152, -4.1283, -2.1932, -2.6104, -1.9580, -3.5252, -1.4919,
         -2.1523, -4.9168],
        [-2.9285, -2.3237, -3.2521, -2.8977, -2.4422, -1.8775, -2.6166, -1.5765,
         -1.6758, -3.0381],
        [-4.6495, -2.2351, -2.8170, -1.9827, -1.9888, -2.8896, -1.1889, -2.2132,
         -3.2881, -3.1634]])

In [8]:
(x.exp() / x.exp().sum(dim=1, keepdim=True)).log()

tensor([[-3.9745, -1.9283, -1.8805, -3.5326, -4.6810, -0.7468, -4.0603, -2.0907,
         -3.9964, -4.4486],
        [-1.4806, -2.7260, -3.4181, -5.7936, -2.8813, -4.7144, -0.8175, -3.8692,
         -2.3374, -3.0540],
        [-4.4816, -1.3152, -4.1283, -2.1932, -2.6104, -1.9580, -3.5252, -1.4919,
         -2.1523, -4.9168],
        [-2.9285, -2.3237, -3.2521, -2.8977, -2.4422, -1.8775, -2.6166, -1.5765,
         -1.6758, -3.0381],
        [-4.6495, -2.2351, -2.8170, -1.9827, -1.9888, -2.8896, -1.1889, -2.2132,
         -3.2881, -3.1634]])

### BatchNorm

In [16]:
x = torch.arange(36, dtype=torch.float32).view(2,2,3,3)
x

tensor([[[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.],
          [ 6.,  7.,  8.]],

         [[ 9., 10., 11.],
          [12., 13., 14.],
          [15., 16., 17.]]],


        [[[18., 19., 20.],
          [21., 22., 23.],
          [24., 25., 26.]],

         [[27., 28., 29.],
          [30., 31., 32.],
          [33., 34., 35.]]]])

In [17]:
x.mean((0,2,3))

tensor([13., 22.])

In [19]:
x.mean((1,2,3))

tensor([ 8.5000, 26.5000])