In [2]:
import numpy as np
import torch

print(torch.__version__)

1.3.1


In [18]:
np_a = np.arange(6)
np_b = np.arange(5,11)
t_a = torch.from_numpy(np_a)
t_b = torch.from_numpy(np_b)
np_a, np_b, t_a, t_b

(array([0, 1, 2, 3, 4, 5]),
 array([ 5,  6,  7,  8,  9, 10]),
 tensor([0, 1, 2, 3, 4, 5]),
 tensor([ 5,  6,  7,  8,  9, 10]))

In [23]:
np_A = np.arange(6).reshape(2,3)
np_B = np.arange(5,11).reshape(2,3)
t_A = torch.from_numpy(np_A)
t_B = torch.from_numpy(np_B)
np_A, np_B, t_A, t_B

(array([[0, 1, 2],
        [3, 4, 5]]), array([[ 5,  6,  7],
        [ 8,  9, 10]]), tensor([[0, 1, 2],
         [3, 4, 5]]), tensor([[ 5,  6,  7],
         [ 8,  9, 10]]))

### element-wise multiply

In [81]:
print(np_a*np_b)
print(np.einsum('i,i->i', np_a, np_b))

print(t_a*t_b)
print(torch.einsum('i,i->i', t_a, t_b))

[ 0  6 14 24 36 50]
[ 0  6 14 24 36 50]
tensor([ 0,  6, 14, 24, 36, 50])
tensor([ 0,  6, 14, 24, 36, 50])


### Hadamard product

In [82]:
print(np_A*np_B)
print(np.einsum('ij,ij->ij', np_A, np_B))

print(t_A*t_B)
print(torch.einsum('ij,ij->ij', t_A, t_B))

[[ 0  6 14]
 [24 36 50]]
[[ 0  6 14]
 [24 36 50]]
tensor([[ 0,  6, 14],
        [24, 36, 50]])
tensor([[ 0,  6, 14],
        [24, 36, 50]])


### element-wise multiply + sum (inner product)

In [37]:
print(np_a.dot(np_b))
print(np.sum(np_a*np_b))
print(np.einsum('i,i->', np_a, np_b))

print(torch.dot(t_a, t_b))
print((t_a*t_b).sum())
print(torch.einsum('i,i->', t_a, t_b))

130
130
130
tensor(130)
tensor(130)
tensor(130)


### outter product

In [40]:
torch.einsum('i,j->ij', t_a, t_b)

tensor([[ 0,  0,  0,  0,  0,  0],
        [ 5,  6,  7,  8,  9, 10],
        [10, 12, 14, 16, 18, 20],
        [15, 18, 21, 24, 27, 30],
        [20, 24, 28, 32, 36, 40],
        [25, 30, 35, 40, 45, 50]])

### trace of vector (sum of main diagonal)

In [52]:
t_A@t_B.T, torch.trace(t_A@t_B.T), torch.einsum('ii', t_A@t_B.T)

(tensor([[ 20,  29],
         [ 74, 110]]), tensor(130), tensor(130))

### sum alone axis

In [56]:
t_A, torch.sum(t_A, dim=1), torch.einsum('ij -> i', t_A)

(tensor([[0, 1, 2],
         [3, 4, 5]]), tensor([ 3, 12]), tensor([ 3, 12]))

### Batch Matrix Multiplicatiot

In [77]:
t_Batch = torch.stack([t_A, t_B])
t_Batch, t_Batch.shape

(tensor([[[ 0,  1,  2],
          [ 3,  4,  5]],
 
         [[ 5,  6,  7],
          [ 8,  9, 10]]]), torch.Size([2, 2, 3]))

In [78]:
torch.einsum('bik, bjk -> bij', t_Batch, t_Batch)

tensor([[[  5,  14],
         [ 14,  50]],

        [[110, 164],
         [164, 245]]])

In [80]:
# same as
torch.stack([t_A@t_A.T, t_B@t_B.T])

tensor([[[  5,  14],
         [ 14,  50]],

        [[110, 164],
         [164, 245]]])

### Advanced examples - check below for explanation

In [57]:
a = np.arange(24).reshape(6,4)
b = np.arange(6)
a, b

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([0, 1, 2, 3, 4, 5]))

In [58]:
np.einsum('ij, i->j', a,b)  # Column sum (a.T*b).T.sum(axis=0)

array([220, 235, 250, 265])

In [59]:
 np.einsum('ij, i->i', a,b)  # Row sum (a.T*b).T.sum(axis=1)

array([  0,  22,  76, 162, 280, 430])

### Vector & Matrix

In [88]:
t_B

tensor([[ 5,  6,  7],
        [ 8,  9, 10]])

In [89]:
torch.einsum('ij, i -> ij', t_B, torch.tensor([2, 3]))

tensor([[10, 12, 14],
        [24, 27, 30]])

In [90]:
torch.einsum('ij, i -> i', t_B, torch.tensor([2, 3]))

tensor([36, 81])

In [91]:
torch.einsum('ij, i -> j', t_B, torch.tensor([2, 3]))

tensor([34, 39, 44])

In [92]:
torch.einsum('ij, i -> ', t_B, torch.tensor([2, 3]))

tensor(117)

In [98]:
torch.einsum('ji, i -> ji', t_B.T, torch.tensor([2, 3]))

tensor([[10, 24],
        [12, 27],
        [14, 30]])