In [1]:
import numpy as np
import torch

print(torch.__version__)

1.3.1


注意点 saving memory
- `torch.tensor()` always copies data. If you have a Tensor data and just want to change its requires_grad flag, use `requires_grad_()` or `detach()` to avoid a copy. If you have a numpy array and want to avoid a copy, use `torch.as_tensor()`
- 

---

```
# https://pytorch.org/docs/stable/tensors.html?highlight=view#
cuda0 = torch.device('cuda:0')
torch.ones([2, 4], dtype=torch.float64, device=cuda0)
```

### arange, shape, size

#### numpy

In [12]:
# numpy
x = np.arange(12)
x, x.shape, x.size

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,), 12)

In [13]:
x_reshape = x.reshape(3, -1)
x_reshape, x_reshape.shape, x_reshape.size

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4),
 12)

#### pytorch

In [14]:
# pytorch
# tensor.size() 和 numpy 作用的不同
x = torch.arange(12)
x, x.shape, x.size()

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 torch.Size([12]),
 torch.Size([12]))

In [16]:
x_reshape = x.reshape(3, -1)
x_reshape, x_reshape.shape, x_reshape.size()

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 torch.Size([3, 4]),
 torch.Size([3, 4]))

### 初始化, empty, zeros, ones

#### numpy

In [25]:
# np.empty_like
# np.zeros_like
# np.ones_like
np.empty((4,6)), np.zeros((2,3)), np.ones((2,3))

(array([[-0.00000000e+000, -0.00000000e+000,  6.91691904e-323,
          0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          2.51554840e+180, -1.73059616e-077,  4.33161289e-311],
        [ 4.45484690e-143,  1.50008929e+248,  1.72905101e-065,
         -1.49457202e-154, -0.00000000e+000, -0.00000000e+000]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [27]:
np.random.normal(0, 1, size=(2,3))

array([[-0.51854306,  1.35659169,  1.66048253],
       [-0.07988188,  0.63408176, -1.0127638 ]])

#### pytorch

In [29]:
# ~_like
torch.empty((2,3)), torch.zeros((2,3)), torch.ones((2,3))

(tensor([[8.4078e-45, 0.0000e+00, 4.9845e-33],
         [1.4013e-45, 0.0000e+00, 0.0000e+00]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [30]:
# normal distributions of mean=0, variance=1
torch.randn(2, 3)

tensor([[0.1499, 1.0818, 0.7879],
        [2.1625, 0.1207, 0.7539]])

In [43]:
torch.normal(2, 3, size=(1, 4))

tensor([[ 4.5228, -2.1124,  5.2856, -2.5598]])

#### pytorch <-> numpy

In [36]:
torch.tensor([1.,2.]).numpy()

array([1., 2.], dtype=float32)

In [42]:
# torch.from_numpy(np.array([1.,2.]))
torch.tensor(np.array([1.,2.]))

tensor([1., 2.], dtype=torch.float64)

### operation

#### numpy

In [60]:
x = np.array([1, 2, 4, 8])
y = np.array([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # The ** operator is exponentiation

(array([ 3,  4,  6, 10]),
 array([-1,  0,  2,  6]),
 array([ 2,  4,  8, 16]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1,  4, 16, 64]))

#### pytorch

In [66]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0, 1, 2, 4]),
 tensor([ 1,  4, 16, 64]))

In [67]:
x**2, x*x, x.pow(2)

(tensor([ 1,  4, 16, 64]), tensor([ 1,  4, 16, 64]), tensor([ 1,  4, 16, 64]))

### saving memory

In [55]:
# https://d2l.ai/chapter_preliminaries/ndarray.html#saving-memory

a = np.random.normal(size=(2,3))
print(id(a))
a += 1
print(id(a))
a[:] = a + 1
print(id(a))
a = a + 1
print(id(a))

4785746608
4785746608
4785746608
4785749648


In [58]:
a = torch.randn(size=(2,3))
print(id(a))
a += 1
print(id(a))
a[:] = a + 1
print(id(a))
a = a + 1
print(id(a))

4783759440
4783759440
4783759440
4783760880
